(require 'markdown-mode)
(require 'jekyll)
(jekyll-init-keybindings)
(setq jekyll-directory "/Users/jmjeong/Dropbox/Documents/homepage/")
(setq jekyll-post-template "---\nlayout: post\ntitle: %s\nmodified: \ncategory: \ntags: \nimage:\n  feature:\n---\n")
(setq jekyll-post-ext ".md")